<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Post;
use Illuminate\Database\Seeder;

class PostSeeder extends Seeder
{
    public function run(): void
    {
        $posts = [
            ['title' => 'Cara menghitung THR karyawan', 'slug' => 'cara-menghitung-thr-karyawan', 'category_slug' => 'payroll-hr', 'excerpt' => 'Panduan ringkas menghitung THR karyawan tetap maupun masa kerja di bawah satu tahun.', 'meta_title' => 'Cara Menghitung THR Karyawan', 'meta_description' => 'Pelajari cara menghitung THR karyawan dengan rumus sederhana dan contoh praktis.', 'content' => '<h2>Apa itu THR?</h2><p>THR adalah tunjangan yang umum diberikan menjelang hari raya keagamaan. Besarannya biasanya dikaitkan dengan gaji bulanan dan masa kerja.</p><h2>Rumus THR penuh</h2><p>Jika masa kerja sudah mencapai 12 bulan atau lebih, THR umumnya setara satu kali gaji bulanan.</p><h2>Rumus THR proporsional</h2><p>Untuk masa kerja di bawah 12 bulan, hitungannya adalah masa kerja dibagi 12 lalu dikalikan gaji bulanan.</p>'],
            ['title' => 'Cara menghitung gaji bersih bulanan', 'slug' => 'cara-menghitung-gaji-bersih-bulanan', 'category_slug' => 'payroll-hr', 'excerpt' => 'Memahami perbedaan gaji kotor, total potongan, dan gaji bersih yang benar-benar diterima.', 'meta_title' => 'Cara Menghitung Gaji Bersih', 'meta_description' => 'Panduan menghitung gaji bersih dari gaji pokok, tunjangan, dan berbagai potongan.', 'content' => '<h2>Mulai dari total pendapatan</h2><p>Gabungkan gaji pokok dan tunjangan tetap maupun tidak tetap yang relevan.</p><h2>Catat semua potongan</h2><p>Masukkan BPJS, pajak, pinjaman, atau potongan lain agar hasil simulasi lebih realistis.</p><h2>Hitung take home pay</h2><p>Kurangi total pendapatan dengan total potongan untuk mendapatkan estimasi gaji bersih.</p>'],
            ['title' => 'Contoh surat izin kerja yang baik', 'slug' => 'contoh-surat-izin-kerja-yang-baik', 'category_slug' => 'dokumen-kerja', 'excerpt' => 'Format surat izin kerja yang sopan, ringkas, dan jelas untuk kebutuhan kantor.', 'meta_title' => 'Contoh Surat Izin Kerja yang Baik', 'meta_description' => 'Pelajari struktur surat izin kerja yang sopan dan profesional.', 'content' => '<h2>Gunakan bahasa yang jelas</h2><p>Tuliskan tanggal, alasan izin, dan identitas singkat tanpa bertele-tele.</p><h2>Sertakan konteks yang cukup</h2><p>Penerima surat perlu memahami alasan izin dan kapan Anda berencana kembali bekerja.</p><h2>Periksa nada penulisan</h2><p>Surat yang sopan akan lebih mudah diterima dan diproses oleh atasan atau HR.</p>'],
            ['title' => 'Contoh surat resign profesional', 'slug' => 'contoh-surat-resign-profesional', 'category_slug' => 'dokumen-kerja', 'excerpt' => 'Contoh surat resign yang singkat, sopan, dan tetap menjaga hubungan profesional.', 'meta_title' => 'Contoh Surat Resign Profesional', 'meta_description' => 'Lihat struktur surat resign profesional yang tetap sopan dan jelas.', 'content' => '<h2>Jaga nada tetap profesional</h2><p>Surat resign tidak perlu terlalu panjang, tetapi harus tetap menghargai perusahaan dan tim.</p><h2>Sebutkan tanggal efektif</h2><p>Jangan lupa menulis kapan pengunduran diri mulai berlaku agar proses transisi lebih rapi.</p><h2>Tutup dengan apresiasi</h2><p>Ucapan terima kasih membantu menjaga hubungan baik setelah Anda keluar.</p>'],
            ['title' => 'Cara membuat invoice sederhana', 'slug' => 'cara-membuat-invoice-sederhana', 'category_slug' => 'administrasi-bisnis', 'excerpt' => 'Elemen wajib invoice sederhana agar tagihan terlihat profesional dan mudah diproses.', 'meta_title' => 'Cara Membuat Invoice Sederhana', 'meta_description' => 'Panduan membuat invoice sederhana untuk freelancer dan usaha kecil.', 'content' => '<h2>Informasi dasar invoice</h2><p>Invoice perlu memuat nomor, tanggal, data pelanggan, dan identitas penerbit.</p><h2>Rincian item harus jelas</h2><p>Tuliskan nama item, jumlah, harga satuan, dan subtotal agar tidak menimbulkan kebingungan.</p><h2>Pastikan total mudah dibaca</h2><p>Subtotal, pajak, diskon, dan grand total harus ditampilkan secara ringkas.</p>'],
            ['title' => 'Perbedaan invoice dan kwitansi', 'slug' => 'perbedaan-invoice-dan-kwitansi', 'category_slug' => 'administrasi-bisnis', 'excerpt' => 'Invoice dan kwitansi sama-sama penting, tetapi dipakai pada momen yang berbeda.', 'meta_title' => 'Perbedaan Invoice dan Kwitansi', 'meta_description' => 'Pahami perbedaan invoice dan kwitansi dalam proses administrasi bisnis.', 'content' => '<h2>Invoice diterbitkan sebelum pembayaran</h2><p>Invoice berfungsi sebagai tagihan atau permintaan pembayaran dari penjual kepada pembeli.</p><h2>Kwitansi menjadi bukti pembayaran</h2><p>Kwitansi menunjukkan bahwa pembayaran telah diterima.</p><h2>Keduanya saling melengkapi</h2><p>Dalam administrasi bisnis yang rapi, invoice dan kwitansi biasanya dipakai berpasangan.</p>'],
            ['title' => 'Contoh berita acara serah terima barang', 'slug' => 'contoh-berita-acara-serah-terima-barang', 'category_slug' => 'dokumen-kerja', 'excerpt' => 'Berita acara membantu proses serah terima barang atau dokumen menjadi lebih tertib.', 'meta_title' => 'Contoh Berita Acara Serah Terima Barang', 'meta_description' => 'Panduan dan contoh berita acara serah terima barang yang ringkas.', 'content' => '<h2>Fungsi berita acara</h2><p>Dokumen ini membantu mencatat detail serah terima secara tertulis agar lebih akuntabel.</p><h2>Isi yang perlu dicantumkan</h2><p>Tanggal, pihak yang menyerahkan, pihak yang menerima, serta rincian barang perlu disebutkan jelas.</p><h2>Tambahkan tanda tangan</h2><p>Tanda tangan kedua pihak memperkuat fungsi dokumentasinya.</p>'],
            ['title' => 'Tips membuat CV sederhana', 'slug' => 'tips-membuat-cv-sederhana', 'category_slug' => 'dokumen-kerja', 'excerpt' => 'CV yang sederhana justru sering lebih efektif karena mudah dipindai recruiter.', 'meta_title' => 'Tips Membuat CV Sederhana', 'meta_description' => 'Pelajari cara membuat CV sederhana yang rapi dan efektif.', 'content' => '<h2>Fokus pada informasi penting</h2><p>Ringkasan profil, pengalaman, pendidikan, dan keterampilan inti biasanya sudah cukup.</p><h2>Gunakan format yang mudah dibaca</h2><p>Hindari elemen visual berlebihan yang justru mengganggu isi utama.</p><h2>Sesuaikan dengan posisi</h2><p>CV yang relevan dengan pekerjaan yang dilamar cenderung lebih efektif.</p>'],
            ['title' => 'Cara membuat surat kuasa', 'slug' => 'cara-membuat-surat-kuasa', 'category_slug' => 'dokumen-kerja', 'excerpt' => 'Surat kuasa perlu menjelaskan pihak pemberi kuasa, penerima kuasa, dan ruang lingkupnya.', 'meta_title' => 'Cara Membuat Surat Kuasa', 'meta_description' => 'Panduan singkat menulis surat kuasa sederhana dan jelas.', 'content' => '<h2>Tentukan identitas para pihak</h2><p>Nama, alamat, dan identitas penting perlu ditulis dengan jelas.</p><h2>Jelaskan ruang lingkup kuasa</h2><p>Sebutkan tindakan atau kewenangan apa saja yang diberikan.</p><h2>Perhatikan konteks penggunaan</h2><p>Untuk kebutuhan resmi tertentu, Anda mungkin perlu menyesuaikan format dengan instansi terkait.</p>'],
            ['title' => 'Template dokumen kerja yang sering dibutuhkan', 'slug' => 'template-dokumen-kerja-yang-sering-dibutuhkan', 'category_slug' => 'administrasi-bisnis', 'excerpt' => 'Daftar template kerja yang paling sering dipakai agar proses administrasi lebih cepat.', 'meta_title' => 'Template Dokumen Kerja yang Sering Dibutuhkan', 'meta_description' => 'Rekomendasi template dokumen kerja yang paling sering dipakai sehari-hari.', 'content' => '<h2>Mulai dari kebutuhan yang paling sering</h2><p>Surat izin, surat resign, invoice, dan CV termasuk dokumen yang umum dicari pengguna.</p><h2>Gunakan template sebagai draft awal</h2><p>Template mempercepat pekerjaan, tetapi tetap perlu disesuaikan dengan konteks nyata.</p><h2>Simpan versi yang rapi</h2><p>Dokumen yang mudah dicari dan mudah diperbarui akan menghemat waktu dalam jangka panjang.</p>'],
        ];

        foreach ($posts as $index => $postData) {
            $categorySlug = $postData['category_slug'];
            unset($postData['category_slug']);

            Post::updateOrCreate(
                ['slug' => $postData['slug']],
                array_merge($postData, [
                    'category_id' => Category::where('slug', $categorySlug)->value('id'),
                    'status' => 'published',
                    'published_at' => now()->subDays(10 - min($index, 9)),
                ]),
            );
        }
    }
}
