<?php

use App\Http\Controllers\BlogController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\GeneratorController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PageController;
use App\Http\Controllers\SeoController;
use App\Http\Controllers\TemplateController;
use App\Http\Controllers\ToolController;
use Illuminate\Support\Facades\Route;

Route::get('/', HomeController::class)->name('home');

Route::get('/tools', [ToolController::class, 'index'])->name('tools.index');
Route::get('/tools/{slug}', [ToolController::class, 'show'])->name('tools.show');
Route::post('/tools/kalkulator-thr/calculate', [ToolController::class, 'calculateThr'])->middleware('throttle:20,1')->name('tools.thr.calculate');
Route::post('/tools/kalkulator-gaji-bersih/calculate', [ToolController::class, 'calculateSalary'])->middleware('throttle:20,1')->name('tools.salary.calculate');
Route::post('/tools/kalkulator-lembur/calculate', [ToolController::class, 'calculateOvertime'])->middleware('throttle:20,1')->name('tools.overtime.calculate');
Route::post('/tools/kalkulator-fee-konsultan-pajak/calculate', [ToolController::class, 'calculateTaxConsultantFee'])->middleware('throttle:20,1')->name('tools.tax-consultant-fee.calculate');
Route::post('/tools/kalkulator-fee-accounting-service/calculate', [ToolController::class, 'calculateAccountingServiceFee'])->middleware('throttle:20,1')->name('tools.accounting-service-fee.calculate');
Route::post('/tools/kalkulator-fee-audit/calculate', [ToolController::class, 'calculateAuditFee'])->middleware('throttle:20,1')->name('tools.audit-fee.calculate');
Route::post('/tools/generator-invoice/calculate', [GeneratorController::class, 'previewInvoice'])->middleware('throttle:20,1')->name('tools.invoice.calculate');
Route::post('/tools/generator-invoice/preview', [GeneratorController::class, 'previewInvoice'])->middleware('throttle:20,1')->name('tools.invoice.preview');
Route::post('/tools/generator-invoice/pdf', [GeneratorController::class, 'downloadInvoice'])->middleware('throttle:10,1')->name('tools.invoice.pdf');
Route::post('/tools/generator-invoice/download', [GeneratorController::class, 'downloadInvoice'])->middleware('throttle:10,1')->name('tools.invoice.download');
Route::post('/tools/generator-invoice/print', [GeneratorController::class, 'printInvoice'])->middleware('throttle:10,1')->name('tools.invoice.print');
Route::post('/tools/generator-kwitansi/preview', [GeneratorController::class, 'previewReceipt'])->middleware('throttle:20,1')->name('tools.receipt.preview');
Route::post('/tools/generator-kwitansi/download', [GeneratorController::class, 'downloadReceipt'])->middleware('throttle:10,1')->name('tools.receipt.download');
Route::post('/tools/generator-kwitansi/print', [GeneratorController::class, 'printReceipt'])->middleware('throttle:10,1')->name('tools.receipt.print');
Route::post('/tools/generator-berita-acara/preview', [GeneratorController::class, 'previewMinutes'])->middleware('throttle:20,1')->name('tools.minutes.preview');
Route::post('/tools/generator-berita-acara/download', [GeneratorController::class, 'downloadMinutes'])->middleware('throttle:10,1')->name('tools.minutes.download');
Route::post('/tools/generator-berita-acara/print', [GeneratorController::class, 'printMinutes'])->middleware('throttle:10,1')->name('tools.minutes.print');
Route::post('/tools/generator-surat-lamaran-kerja/preview', [GeneratorController::class, 'previewApplicationLetter'])->middleware('throttle:20,1')->name('tools.application-letter.preview');
Route::post('/tools/generator-surat-lamaran-kerja/download', [GeneratorController::class, 'downloadApplicationLetterText'])->middleware('throttle:10,1')->name('tools.application-letter.download');
Route::post('/tools/generator-surat-lamaran-kerja/pdf', [GeneratorController::class, 'downloadApplicationLetter'])->middleware('throttle:10,1')->name('tools.application-letter.pdf');
Route::post('/tools/generator-surat-lamaran-kerja/print', [GeneratorController::class, 'printApplicationLetter'])->middleware('throttle:10,1')->name('tools.application-letter.print');
Route::post('/tools/generator-quotation/preview', [GeneratorController::class, 'previewQuotation'])->middleware('throttle:20,1')->name('tools.quotation.preview');
Route::post('/tools/generator-quotation/download', [GeneratorController::class, 'downloadQuotationText'])->middleware('throttle:10,1')->name('tools.quotation.download');
Route::post('/tools/generator-quotation/pdf', [GeneratorController::class, 'downloadQuotation'])->middleware('throttle:10,1')->name('tools.quotation.pdf');
Route::post('/tools/generator-quotation/print', [GeneratorController::class, 'printQuotation'])->middleware('throttle:10,1')->name('tools.quotation.print');
Route::post('/tools/generator-sop/preview', [GeneratorController::class, 'previewSop'])->middleware('throttle:20,1')->name('tools.sop.preview');
Route::post('/tools/generator-sop/download', [GeneratorController::class, 'downloadSopText'])->middleware('throttle:10,1')->name('tools.sop.download');
Route::post('/tools/generator-sop/pdf', [GeneratorController::class, 'downloadSop'])->middleware('throttle:10,1')->name('tools.sop.pdf');
Route::post('/tools/generator-sop/print', [GeneratorController::class, 'printSop'])->middleware('throttle:10,1')->name('tools.sop.print');
Route::post('/tools/generator-job-description/preview', [GeneratorController::class, 'previewJobDescription'])->middleware('throttle:20,1')->name('tools.job-description.preview');
Route::post('/tools/generator-job-description/download', [GeneratorController::class, 'downloadJobDescriptionText'])->middleware('throttle:10,1')->name('tools.job-description.download');
Route::post('/tools/generator-job-description/pdf', [GeneratorController::class, 'downloadJobDescription'])->middleware('throttle:10,1')->name('tools.job-description.pdf');
Route::post('/tools/generator-job-description/print', [GeneratorController::class, 'printJobDescription'])->middleware('throttle:10,1')->name('tools.job-description.print');
Route::post('/tools/simulasi-pertanyaan-interview/preview', [GeneratorController::class, 'previewInterviewSimulation'])->middleware('throttle:20,1')->name('tools.interview-simulation.preview');
Route::post('/tools/simulasi-pertanyaan-interview/download', [GeneratorController::class, 'downloadInterviewSimulationText'])->middleware('throttle:10,1')->name('tools.interview-simulation.download');
Route::post('/tools/simulasi-pertanyaan-interview/pdf', [GeneratorController::class, 'downloadInterviewSimulation'])->middleware('throttle:10,1')->name('tools.interview-simulation.pdf');
Route::post('/tools/simulasi-pertanyaan-interview/print', [GeneratorController::class, 'printInterviewSimulation'])->middleware('throttle:10,1')->name('tools.interview-simulation.print');
Route::post('/tools/interview-answer-star/preview', [GeneratorController::class, 'previewInterviewStarAnswer'])->middleware('throttle:20,1')->name('tools.interview-star.preview');
Route::post('/tools/interview-answer-star/download', [GeneratorController::class, 'downloadInterviewStarAnswerText'])->middleware('throttle:10,1')->name('tools.interview-star.download');
Route::post('/tools/interview-answer-star/pdf', [GeneratorController::class, 'downloadInterviewStarAnswer'])->middleware('throttle:10,1')->name('tools.interview-star.pdf');
Route::post('/tools/interview-answer-star/print', [GeneratorController::class, 'printInterviewStarAnswer'])->middleware('throttle:10,1')->name('tools.interview-star.print');
Route::post('/tools/linkedin-headline-about-generator/preview', [GeneratorController::class, 'previewLinkedInProfile'])->middleware('throttle:20,1')->name('tools.linkedin-profile.preview');
Route::post('/tools/linkedin-headline-about-generator/download', [GeneratorController::class, 'downloadLinkedInProfileText'])->middleware('throttle:10,1')->name('tools.linkedin-profile.download');
Route::post('/tools/linkedin-headline-about-generator/pdf', [GeneratorController::class, 'downloadLinkedInProfile'])->middleware('throttle:10,1')->name('tools.linkedin-profile.pdf');
Route::post('/tools/linkedin-headline-about-generator/print', [GeneratorController::class, 'printLinkedInProfile'])->middleware('throttle:10,1')->name('tools.linkedin-profile.print');
Route::post('/tools/job-description-matcher/preview', [GeneratorController::class, 'previewJobDescriptionMatcher'])->middleware('throttle:20,1')->name('tools.jd-matcher.preview');
Route::post('/tools/job-description-matcher/download', [GeneratorController::class, 'downloadJobDescriptionMatcherText'])->middleware('throttle:10,1')->name('tools.jd-matcher.download');
Route::post('/tools/job-description-matcher/pdf', [GeneratorController::class, 'downloadJobDescriptionMatcher'])->middleware('throttle:10,1')->name('tools.jd-matcher.pdf');
Route::post('/tools/job-description-matcher/print', [GeneratorController::class, 'printJobDescriptionMatcher'])->middleware('throttle:10,1')->name('tools.jd-matcher.print');
Route::post('/tools/ats-cv-checker/preview', [GeneratorController::class, 'previewAtsCvChecker'])->middleware('throttle:20,1')->name('tools.ats-cv-checker.preview');
Route::post('/tools/ats-cv-checker/download', [GeneratorController::class, 'downloadAtsCvCheckerText'])->middleware('throttle:10,1')->name('tools.ats-cv-checker.download');
Route::post('/tools/ats-cv-checker/pdf', [GeneratorController::class, 'downloadAtsCvChecker'])->middleware('throttle:10,1')->name('tools.ats-cv-checker.pdf');
Route::post('/tools/ats-cv-checker/print', [GeneratorController::class, 'printAtsCvChecker'])->middleware('throttle:10,1')->name('tools.ats-cv-checker.print');
Route::post('/tools/generator-laporan-kerja-harian/preview', [GeneratorController::class, 'previewDailyWorkReport'])->middleware('throttle:20,1')->name('tools.daily-work-report.preview');
Route::post('/tools/generator-laporan-kerja-harian/download', [GeneratorController::class, 'downloadDailyWorkReportText'])->middleware('throttle:10,1')->name('tools.daily-work-report.download');
Route::post('/tools/generator-laporan-kerja-harian/word', [GeneratorController::class, 'downloadDailyWorkReportWord'])->middleware('throttle:10,1')->name('tools.daily-work-report.word');
Route::post('/tools/generator-laporan-kerja-harian/pdf', [GeneratorController::class, 'downloadDailyWorkReport'])->middleware('throttle:10,1')->name('tools.daily-work-report.pdf');
Route::post('/tools/generator-laporan-kerja-harian/print', [GeneratorController::class, 'printDailyWorkReport'])->middleware('throttle:10,1')->name('tools.daily-work-report.print');
Route::post('/tools/generator-cv-ats/calculate', [ToolController::class, 'calculateCvAts'])->middleware('throttle:20,1')->name('tools.cv-ats.calculate');
Route::post('/tools/generator-cv-ats/pdf', [ToolController::class, 'cvAtsPdf'])->middleware('throttle:10,1')->name('tools.cv-ats.pdf');
Route::post('/tools/generator-cv-ats/word', [ToolController::class, 'cvAtsWord'])->middleware('throttle:10,1')->name('tools.cv-ats.word');
Route::post('/tools/generator-surat-izin/calculate', [GeneratorController::class, 'previewLetter'])->middleware('throttle:20,1')->name('tools.leave-letter.calculate');
Route::post('/tools/generator-surat-izin/preview', [GeneratorController::class, 'previewLetter'])->middleware('throttle:20,1')->name('tools.leave-letter.preview');
Route::post('/tools/generator-surat-izin/download', [GeneratorController::class, 'downloadLetterText'])->middleware('throttle:10,1')->name('tools.leave-letter.download');
Route::post('/tools/generator-surat-izin/pdf', [GeneratorController::class, 'downloadLetterPdf'])->middleware('throttle:10,1')->name('tools.leave-letter.pdf');
Route::post('/tools/generator-surat-izin/print', [GeneratorController::class, 'printLetter'])->middleware('throttle:10,1')->name('tools.leave-letter.print');

Route::get('/template', [TemplateController::class, 'index'])->name('templates.index');
Route::get('/template/{slug}', [TemplateController::class, 'show'])->name('templates.show');
Route::get('/template/{slug}/download.txt', [TemplateController::class, 'download'])->name('templates.download');
Route::get('/template/{slug}/download.doc', [TemplateController::class, 'downloadWord'])->name('templates.download-word');

Route::get('/blog', [BlogController::class, 'index'])->name('blog.index');
Route::get('/blog/{slug}', [BlogController::class, 'show'])->name('blog.show');

Route::get('/about', [PageController::class, 'show'])->defaults('slug', 'about')->name('pages.about');
Route::get('/contact', [PageController::class, 'show'])->defaults('slug', 'contact')->name('pages.contact');
Route::post('/contact', [ContactController::class, 'store'])->middleware('throttle:5,10')->name('contact.store');
Route::get('/privacy-policy', [PageController::class, 'show'])->defaults('slug', 'privacy-policy')->name('pages.privacy-policy');
Route::get('/terms', [PageController::class, 'show'])->defaults('slug', 'terms')->name('pages.terms');
Route::get('/disclaimer', [PageController::class, 'show'])->defaults('slug', 'disclaimer')->name('pages.disclaimer');
Route::get('/pages/{slug}', [PageController::class, 'show'])->name('pages.show');

Route::get('/sitemap.xml', [SeoController::class, 'sitemap'])->name('seo.sitemap');
Route::get('/robots.txt', [SeoController::class, 'robots'])->name('seo.robots');
